version: '2.3'


services:
  tf_unet:
    image: <your_docker_image>:<tag>
    runtime: nvidia
    ports:
     - "port1:port1"
     - "port2:port2"
    volumes:
     - <path_to_this_repo>:/app/repo/
    command: jupyter lab --notebook-dir=./repo/ --ip=0.0.0.0 --port=<port1>  --no-browser --allow-root
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1,2
    shm_size: '32gb'
    # environment: # or I could do this
    #   - NVIDIA_VISIBLE_DEVICES=0
    tty: true


# sudo docker-compose -f docker-compose.yml up
# sudo docker exec -it <container-id> /bin/bash
